Install websocket dependency
Perhaps web3's dependencies aren't configured properly, since on circle,
I get:
```
/home/circleci/force-move-games/packages/fmg-simple-adjudicator/node_modules/web3-providers-ws/src/index.js:1
Error: Cannot find module 'websocket'
```