remove embeddedapplication (for now)
It causes:

CompilerError: Stack too deep when compiling inline assembly: Variable dataEnd is 5 slot(s) too deep inside the stack.

I do not know why