chore: interop test no longer exits with an error code
Before this commit, the process exits with
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.0.9)