chore: hardcode resolution version
Without @types/express hardcoding, we see:
@statechannels/client-api-schema:
monorepo/node_modules/@types/express/index.d.ts(58,29): error TS2694:
Namespace 'serveStatic' has no exported member 'RequestHandlerConstructor'.

@types/react is updated to match the version in the docs-website and
xstate-wallet packages.